# Generated by Django 5.1.4 on 2024-12-20 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('pack_size', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('manufacturer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='DeliveredDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtech.delivery')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtech.drug')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='drugs',
            field=models.ManyToManyField(through='medtech.DeliveredDrug', to='medtech.drug'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wake_up_time', models.TimeField()),
                ('sleep_time', models.TimeField()),
                ('breakfast_time', models.TimeField()),
                ('lunch_time', models.TimeField()),
                ('dinner_time', models.TimeField()),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_qty', models.FloatField()),
                ('afternoon_qty', models.FloatField()),
                ('night_qty', models.FloatField()),
                ('custom_qty', models.FloatField()),
                ('custom_time', models.TimeField()),
                ('amt_remaining', models.FloatField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtech.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('drugs', models.ManyToManyField(through='medtech.PrescribedDrug', to='medtech.drug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prescribeddrug',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtech.prescription'),
        ),
    ]
