# Generated by Django 5.1.4 on 2024-12-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sleep_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='wake_up_time',
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='afternoon_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='amt_remaining',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='custom_qty',
            field=models.FloatField(blank=True, null=True, verbose_name='Custom qty (if applicable)'),
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='custom_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Custom time (if applicable)'),
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='morning_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='night_qty',
            field=models.FloatField(default=0),
        ),
    ]
