# Generated by Django 5.1.4 on 2024-12-22 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtech', '0003_patient_name_alter_prescribeddrug_amt_remaining_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribeddrug',
            name='custom_qty',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Custom qty (if applicable)'),
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='custom_time',
            field=models.TimeField(blank=True, editable=False, null=True, verbose_name='Custom time (if applicable)'),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('taken', models.BooleanField(default=False)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtech.drug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
