version: 3

tasks:
  djdev:
    dir: backend
    cmds:
      - python3 manage.py runserver 0.0.0.0:8000
    desc: Run Django development server

  uidev:
    dir: frontend
    cmds:
      - npm run dev
    desc: Run Nextjs development server

  scheduler:
    dir: backend
    cmds:
      - python3 scheduler.py

  dev:
    cmds:
      - task -p djdev uidev
    desc: Run all development servers